name: Build and deploy container app to Azure Web App - eureka-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55

      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-eureka:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@1384c340ab2dda50fed2bee3041d1d87018aa5e8
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_901AF2A368124E1697A2EC9953B03257 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD7A00C26A4F4FD78D434AB3CB6C16D1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_71430A1328E740DA8BC5C94F7086117B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@3f1742a3b209ebd19d82b914f43fe1d6b919e536
        with:
          app-name: 'eureka-server'
          slot-name: 'Production'
          images: '${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-eureka:latest'