name: Build and deploy container app to Azure Web App - eureka-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: index.docker.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_F0042D307AF946F49301E93EE7EC4186 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_58848738B3D14718917F3218794EFFE8 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-eureka:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D7C6226383CF458EBD28AD7724FECEF6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_13F78BA1592F4E2CA89EC8D1D8193A1A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B22E49475F72421A90E81BD346BEB373 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eureka-server'
          slot-name: 'Production'
          images: raydberg25/fitdesk-eureka:latest
          