# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eureka-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: index.docker.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_DF7E55AC18124BA2ACDBF4A372AD1A9F }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_A1CDF3AAF09F46B5B7EA542C4BFC985C }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_DF7E55AC18124BA2ACDBF4A372AD1A9F }}/raydberg25/fitdesk-eureka:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_901AF2A368124E1697A2EC9953B03257 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DD7A00C26A4F4FD78D434AB3CB6C16D1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_71430A1328E740DA8BC5C94F7086117B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eureka-server'
          slot-name: 'Production'
          images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_DF7E55AC18124BA2ACDBF4A372AD1A9F }}/raydberg25/fitdesk-eureka:${{ github.sha }}'
          