name: CI / SonarCloud
on:
  pull_request:
  push:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    env:
      SONAR_PR_BRANCH: ${{github.head_ref}}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build & Run Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{secrets.PROJECT_KEY}}
          SONAR_ORG_KEY: ${{secrets.PROJECT_KEY}}
          SONAR_PULL_REQUEST_KEY: ${{github.event.pull_request.number}}
          SONAR_PULL_REQUEST_BASE: ${{github.base_refr}}
        run: |
          mvn -B -DskipTests verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORG_KEY \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.pullrequest.key=$SONAR_PULL_REQUEST_KEY \
            -Dsonar.pullrequest.branch=$SONAR_PR_BRANCH \
            -Dsonar.pullrequest.base=$SONAR_PULL_REQUEST_BASE

  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Log in to Docker Hub
        uses: docker/login-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55
      - name: Build and push image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-eureka:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-eureka:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/fitdesk-eureka:buildcache,mode=max
